### ISSUE TITLE
token_shift

### ISSUE THREAD

**Issue by LanZhenFeng** [lucidrains/recurrent-memory-transformer-pytorch#3]
Hello, I'm sorry to bother you, but this issue is troubling me. Specifically, what is the purpose of token_shift and why is it needed? I hope to receive a detailed explanation from you.

**Comment by lucidrains** [comment]
@LanZhenFeng hey Lan, no problem! token shift was actually a technique used by Bo Peng in his language model, RWKV (cited at the bottom of the readme). it basically is a cheap way to give relative positions. You can think of it as a depthwise conv with a fixed kernel. i decided to offer it as an alternative to rotary embeddings, because i wasn't confident about how to present the positions between the memory vs the main sequence tokens

**Comment by lucidrains** [comment]
the correct way may be to do the self and cross attention to-and-from memory tokens separately, with main sequence queries and keys without the rotary embeddings, but it seems like it would complicate the elegant scheme

**Comment by DaehanKim** [comment]
I was also wondering about this. Thank you for this repo! @lucidrains

**Comment by lucidrains** [comment]
@DaehanKim yea no problem! i'll complete the rotary embeddings today, still need to make it work for the sliding windows, i'm just not entirely sure the way i did the [relative positions of memory to sequence token](https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/main/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L350) makes sense
